### ISSUE TITLE
opencv 一直有报错

### ISSUE THREAD

**Issue by Yiyiyimu** [TonyJiangWJ/Ant-Forest#101]
```
2021-05-13 20:42:02.743 发生异常 [JavaException: org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
]
2021-05-13 20:42:02.743 fileName:file:///android_asset/modules/__images__.js line:232 typeof e:object
2021-05-13 20:42:02.745 org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'


CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
]
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Unknown Source:3)
	at com.stardust.autojs.core.opencv.Mat.<init>(Unknown Source:0)
	at com.stardust.autojs.core.image.ImageWrapper.getMat(Unknown Source:71)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source:4)
	at org.mozilla.javascript.JavaMembers.get(Unknown Source:56)
	at org.mozilla.javascript.NativeJavaObject.get(Unknown Source:16)
	at org.mozilla.javascript.ScriptableObject.getProperty(Unknown Source:1)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(Unknown Source:0)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(Unknown Source:6)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source:1531)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source:69)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:20)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source:0)
	at okhttp3.internal.io.gi0.doTopCall(:2)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source:33)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source:22)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(Unknown Source:46)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(Unknown Source:15)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(Unknown Source:0)
	at okhttp3.internal.io.ჴ.run(:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:27)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:1)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(Unknown Source:55)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:4)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:27)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(Unknown Source:41)
	at java.lang.Thread.run(Thread.java:923)
2021-05-13 20:42:04.285 发生异常 [JavaException: com.stardust.autojs.runtime.exception.ScriptInterruptedException: null]
2021-05-13 20:42:29.817 发生异常 [JavaException: org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/parallel.cpp:240: error: (-2:Unspecified error) in function 'void {anonymous}::ParallelLoopBodyWrapperContext::finalize()'
> Exception in parallel_for() body: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
> ]
2021-05-13 20:42:29.818 fileName:file:///android_asset/modules/__images__.js line:317 typeof e:object
2021-05-13 20:42:29.819 org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/parallel.cpp:240: error: (-2:Unspecified error) in function 'void {anonymous}::ParallelLoopBodyWrapperContext::finalize()'
> Exception in parallel_for() body: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
> 

CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/parallel.cpp:240: error: (-2:Unspecified error) in function 'void {anonymous}::ParallelLoopBodyWrapperContext::finalize()'
> Exception in parallel_for() body: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
> ]
	at org.opencv.imgproc.Imgproc.HoughCircles_0(Native Method)
	at org.opencv.imgproc.Imgproc.HoughCircles(Unknown Source:21)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source:4)
	at org.mozilla.javascript.NativeJavaMethod.call(Unknown Source:195)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source:5497)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source:69)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:20)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source:0)
	at okhttp3.internal.io.gi0.doTopCall(:2)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source:33)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source:22)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(Unknown Source:46)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(Unknown Source:15)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(Unknown Source:0)
	at okhttp3.internal.io.ჴ.run(:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:27)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:1)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(Unknown Source:55)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:4)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:27)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(Unknown Source:41)
	at java.lang.Thread.run(Thread.java:923)
2021-05-13 20:42:29.978 执行异常, 1分钟后重新开始InternalError: Cannot convert null to boolean (file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/lib/BaseCommonFunctions.js#112)
2021-05-13 20:42:29.979 fileName:file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/lib/BaseCommonFunctions.js line:112 typeof e:object
2021-05-13 20:42:29.980 Cannot convert null to boolean (file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/lib/BaseCommonFunctions.js#112)

org.mozilla.javascript.EvaluatorException: Cannot convert null to boolean (file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/lib/BaseCommonFunctions.js#112)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(Unknown Source:22)
	at org.mozilla.javascript.Context.reportRuntimeError(Unknown Source:15)
	at org.mozilla.javascript.Context.reportRuntimeError(Unknown Source:13)
	at org.mozilla.javascript.Context.reportRuntimeError2(Unknown Source:4)
	at org.mozilla.javascript.NativeJavaObject.reportConversionError(Unknown Source:10)
	at org.mozilla.javascript.NativeJavaObject.coerceTypeImpl(Unknown Source:384)
	at org.mozilla.javascript.Context.jsToJava(Unknown Source:0)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(Unknown Source:103)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(Unknown Source:11)
	at okhttp3.internal.io.t41.run(:1)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(Unknown Source:44)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(Unknown Source:12)
	at okhttp3.internal.io.s41.invoke(:2)
	at okhttp3.internal.io.fi0$֏.invoke(Unknown Source:2)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy23.filter(Unknown Source)
	at com.stardust.autojs.core.accessibility.AccessibilityBridge.windowRoots(Unknown Source:42)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source:4)
	at org.mozilla.javascript.NativeJavaMethod.call(Unknown Source:195)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source:5497)
	at script(file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/lib/BaseCommonFunctions.js:112)
	at script(file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/lib/BaseCommonFunctions.js:597)
	at script(file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/core/Ant_forest.js:683)
	at script(file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/core/Ant_forest.js:868)
	at script(file:/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/core/Ant_forest.js:912)
	at script(/storage/emulated/0/Scripts/Ant-Forest-1.3.5.1/Ant-Forest-1.3.5.1/main.js:141)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source:69)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:20)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source:0)
	at okhttp3.internal.io.gi0.doTopCall(:2)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source:33)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source:22)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(Unknown Source:46)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(Unknown Source:15)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(Unknown Source:0)
	at okhttp3.internal.io.ჴ.run(:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:27)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:1)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(Unknown Source:55)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:4)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:27)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(Unknown Source:41)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by TonyJiangWJ** [comment]
用的是哪个版本的AutoJS？
建议使用我修改的版本[AutoJS Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk)

**Comment by Yiyiyimu** [comment]
pro 8.7.7-0
嗯我试试，感谢！

**Comment by Yiyiyimu** [comment]
现在没有问题了，再次感谢！

**Comment by TonyJiangWJ** [comment]
嗯 可能后来作者又修改了什么东西，我只在三月份测了Pro9的测试版本
