### ISSUE TITLE
ADB授权截图权限，不再弹窗询问

### ISSUE THREAD

**Issue by TonyJiangWJ** [TonyJiangWJ/Ant-Forest#130]
- 打开开发者选项 开启ADB调试，连接电脑后用ADB命令授权媒体权限
`adb shell appops set ${packageName} PROJECT_MEDIA allow`
- 不会再每次都弹窗是否授权截图权限了
- ${packageName}自行替换成所使用的AutoJS的包名即可 免费版为 `org.autojs.autojs` 修改版 `org.autojs.autojs.modify` Pro `org.autojs.autojspro`

**Comment by TonyJiangWJ** [comment]
https://stackoverflow.com/questions/63039084/android-stop-permission-promt-for-screen-recording

**Comment by ilcf** [comment]
作者推荐使用的AutoJS修改版的package name 是org.autojs.autojs.modify，命令如下：
adb shell pm grant org.autojs.autojs.modify android.permission.WRITE_SECURE_SETTINGS

**Comment by cyanhill** [comment]
最近升级了小米的 HyperOS ，发现需要重新设置下权限，作者推荐使用的 `困鱼` 包名是 `com.taobao.idlefish.x` ，命令如下：
`adb shell pm grant com.taobao.idlefish.x android.permission.WRITE_SECURE_SETTINGS`
`adb shell appops set com.taobao.idlefish.x PROJECT_MEDIA allow`

**Comment by dotama** [comment]
我用的autojs.modify，小米HyperOS试过了，貌似执行这句就够了
`adb shell appops set org.autojs.autojs.modify PROJECT_MEDIA allow`

因为执行下面的报错了😂
```
adb shell pm grant org.autojs.autojs.modify android.permission.WRITE_SECURE_SETTINGS

Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2343)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2371)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1359)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1341)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:559)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:614)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2692)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:291)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6556)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4352)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6540)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)
```

**Comment by cyanhill** [comment]
换了小米15pro，下载最新的困鱼改名成跳跳鱼了，包名为 `com.litiaotiao.app.x`

- `adb shell pm grant com.litiaotiao.app.x android.permission.WRITE_SECURE_SETTINGS`
- `adb shell appops set com.litiaotiao.app.x PROJECT_MEDIA allow`

第一命令报如下错误时，打开 USB调试 下面的 USB调试（安全设置）开关。
每个手机厂商都搞自己的系统，开发者模式按钮搁那创来创去
```shell
adb shell pm grant com.litiaotiao.app.x android.permission.WRITE_SECURE_SETTINGS

Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2400)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2428)
        at com.android.server.permission.access.permission.PermissionService.setRuntimePermissionGranted(PermissionService.kt:780)
        at com.android.server.permission.access.permission.PermissionService.setRuntimePermissionGranted$default(PermissionService.kt:729)
        at com.android.server.permission.access.permission.PermissionService.grantRuntimePermission(PermissionService.kt:688)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:595)
        at android.permission.PermissionManager.grantRuntimePermissionInternal(PermissionManager.java:684)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:647)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2710)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:316)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6779)
        at android.os.Binder.shellCommand(Binder.java:1237)
        at android.os.Binder.onTransact(Binder.java:1050)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4620)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6763)
        at android.os.Binder.execTransactInternal(Binder.java:1512)
        at android.os.Binder.execTransact(Binder.java:1451)
```

**Comment by TonyJiangWJ** [comment]
> 困鱼：授权无障碍adb shell pm grant 'com.taobao.idlefish.x' android.permission.WRITE_SECURE_SETTINGS 撤销授权无障碍adb shell pm revoke 'com.taobao.idlefish.x' android.permission.WRITE_SECURE_SETTINGS 授权截图或投放录屏adb shell appops set 'com.taobao.idlefish.x' PROJECT_MEDIA allow 撤销授权，暂时未知，请教大佬

撤销的命令是将allow改为deny: 
```shell
adb shell appops set 'com.taobao.idlefish.x' PROJECT_MEDIA deny
```
