### ISSUE TITLE
判断列表是否到底报错

### ISSUE THREAD

**Issue by Ehustein** [TonyJiangWJ/Ant-Forest#38]
判断列表是否到底会报错，具体错误信息如下，可以正常运行到结束，但是会卡一会
```
2020-05-16 13:00:05.260 DEBUG [E:6 T:2080] - timeout for finding 没有更多了
2020-05-16 13:00:05.268 ERROR [E:6 T:2080] - java.lang.IllegalMonitorStateException: null

java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1291)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:466)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3452)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:137)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(VMBridge_custom.java:149)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.lambda$invoke$0(VMBridge_custom.java:131)
	at org.mozilla.javascript.-$$Lambda$VMBridge_custom$InterfaceAdapterWrapper$XK1hqYOz19X_TRE0jcwZie74Ua4.run(Unknown Source:13)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(VMBridge_custom.java:140)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(VMBridge_custom.java:132)
	at org.mozilla.javascript.VMBridge_custom.lambda$newInterfaceProxy$0(VMBridge_custom.java:65)
	at org.mozilla.javascript.-$$Lambda$VMBridge_custom$YVyz9uh0Rns0jQ5QbSHESBMT8e0.invoke(Unknown Source:15)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy11.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at com.stardust.autojs.core.looper.TimerThread.run(TimerThread.java:46)
2020-05-16 13:00:05.275 DEBUG [E:6 T:2080] - 预加载线程进入循环体
```

**Comment by TonyJiangWJ** [comment]
这个不影响的，直接删除或者注释 `core/FriendListScanner.js``line:109` 的代码即可
```javascript
} catch (e) {
  //_commonFunctions.printExceptionStack(e)
}
```
