### ISSUE TITLE
解锁后不马上开始收取，设置自动锁屏不执行

### ISSUE THREAD

**Issue by nmcq** [TonyJiangWJ/Ant-Forest#58]
解锁后需要3分钟或4分钟开始收取，另在config中配置自动锁屏，代码测试无问题，收集完毕后不锁屏。

**Comment by TonyJiangWJ** [comment]
自己检查一下代码是不是写错了什么东西。自动锁屏不同手机也需要自行写代码 不是config配一下就完事的，相关的都写在README里面了 麻烦认真看一下。
另外提问题带上日志，就一句话鬼知道问题出在哪里

**Comment by nmcq** [comment]
放一部分
2020-09-12 01:10:48.927 LOG [E:32 T:3118] - ======尝试加入任务队列，并关闭重复运行的脚本=======
2020-09-12 01:10:48.947 LOG [E:32 T:3118] - ======加入任务队列成功=======
2020-09-12 01:10:48.949 LOG [E:32 T:3118] - ======基于图像分析模式：加载dex=======
2020-09-12 01:10:49.51 LOG [E:32 T:3118] - =======加载dex完成=======
2020-09-12 01:10:49.183 LOG [E:32 T:3118] - ======校验无障碍功能======
2020-09-12 01:10:49.191 LOG [E:32 T:3118] - ---前置校验完成;启动系统--->>>>
2020-09-12 01:10:49.193 LOG [E:32 T:3118] - 版本信息：develop_version
2020-09-12 01:10:49.195 LOG [E:32 T:3118] - AutoJS version: 4.1.1 Alpha2
2020-09-12 01:10:49.196 LOG [E:32 T:3118] - device info: HUAWEI VOG-AL10 10
2020-09-12 01:10:49.197 LOG [E:32 T:3118] - 运行模式：多脚本调度运行 计时模式，超时时间：60 基于图像分析-使用OCR识别倒计时  排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 速度：200ms 底部高度：200
2020-09-12 01:10:49.198 LOG [E:32 T:3118] - 设备分辨率：[1, 1]
2020-09-12 01:10:49.202 LOG [E:32 T:3118] - ======解锁并校验截图权限======
2020-09-12 01:10:49.204 LOG [E:32 T:3118] - 已解锁
2020-09-12 01:10:49.204 LOG [E:32 T:3118] - 不需要重新锁定屏幕
2020-09-12 01:10:49.205 LOG [E:32 T:3118] - 解锁成功
2020-09-12 01:10:51.332 LOG [E:32 T:3118] - 请求截屏权限成功
2020-09-12 01:11:25.288 LOG [E:35 T:3139] - ======尝试加入任务队列，并关闭重复运行的脚本=======
2020-09-12 01:11:25.300 LOG [E:35 T:3139] - ======加入任务队列成功=======
2020-09-12 01:11:25.301 LOG [E:35 T:3139] - ======基于图像分析模式：加载dex=======
2020-09-12 01:11:25.307 LOG [E:35 T:3139] - =======加载dex完成=======
2020-09-12 01:11:26.55 LOG [E:35 T:3139] - ======校验无障碍功能======
2020-09-12 01:11:26.63 LOG [E:35 T:3139] - ---前置校验完成;启动系统--->>>>
2020-09-12 01:11:26.65 LOG [E:35 T:3139] - 版本信息：develop_version
2020-09-12 01:11:26.67 LOG [E:35 T:3139] - AutoJS version: 4.1.1 Alpha2
2020-09-12 01:11:26.68 LOG [E:35 T:3139] - device info: HUAWEI VOG-AL10 10
2020-09-12 01:11:26.69 LOG [E:35 T:3139] - 运行模式：多脚本调度运行 计时模式，超时时间：60 基于图像分析-使用OCR识别倒计时  排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 速度：200ms 底部高度：200
2020-09-12 01:11:26.70 LOG [E:35 T:3139] - 设备分辨率：[2340, 1080]
2020-09-12 01:11:26.73 LOG [E:35 T:3139] - ======解锁并校验截图权限======
2020-09-12 01:11:26.75 LOG [E:35 T:3139] - 已解锁
2020-09-12 01:11:26.75 LOG [E:35 T:3139] - 不需要重新锁定屏幕
2020-09-12 01:11:26.76 LOG [E:35 T:3139] - 解锁成功
2020-09-12 01:11:28.195 LOG [E:35 T:3139] - 请求截屏权限成功
2020-09-12 01:16:23.120 LOG [E:0 T:2701] - ======尝试加入任务队列，并关闭重复运行的脚本=======
2020-09-12 01:16:23.172 LOG [E:0 T:2701] - ======加入任务队列成功=======
2020-09-12 01:16:23.176 LOG [E:0 T:2701] - ======基于图像分析模式：加载dex=======
2020-09-12 01:16:23.193 LOG [E:0 T:2701] - =======加载dex完成=======
2020-09-12 01:16:23.422 LOG [E:0 T:2701] - ======校验无障碍功能======
2020-09-12 01:16:23.436 LOG [E:0 T:2701] - ---前置校验完成;启动系统--->>>>
2020-09-12 01:16:23.440 LOG [E:0 T:2701] - 版本信息：develop_version
2020-09-12 01:16:23.446 LOG [E:0 T:2701] - AutoJS version: 4.1.1 Alpha2
2020-09-12 01:16:23.449 LOG [E:0 T:2701] - device info: HUAWEI VOG-AL10 10
2020-09-12 01:16:23.452 LOG [E:0 T:2701] - 运行模式：多脚本调度运行 计时模式，超时时间：60 基于图像分析-使用OCR识别倒计时  排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 速度：200ms 底部高度：200
2020-09-12 01:16:23.454 LOG [E:0 T:2701] - 设备分辨率：[1080, 2340]
2020-09-12 01:16:23.464 LOG [E:0 T:2701] - ======解锁并校验截图权限======
2020-09-12 01:16:23.468 LOG [E:0 T:2701] - 已解锁
2020-09-12 01:16:23.471 LOG [E:0 T:2701] - 不需要重新锁定屏幕
2020-09-12 01:16:23.474 LOG [E:0 T:2701] - 解锁成功
2020-09-12 01:16:25.636 LOG [E:0 T:2701] - 请求截屏权限成功
2020-09-12 01:17:36.327 LOG [E:0 T:2701] - 已解锁
2020-09-12 01:17:36.330 LOG [E:0 T:2701] - 不需要重新锁定屏幕
2020-09-12 01:17:41.864 LOG [E:0 T:2701] - 立即开始
2020-09-12 01:17:41.876 LOG [E:0 T:2701] - 日期：2020-09-12，启动时能量:undefinedg
2020-09-12 01:18:16.992 LOG [E:1 T:2732] - ======尝试加入任务队列，并关闭重复运行的脚本=======
2020-09-12 01:18:17.8 LOG [E:1 T:2732] - ======加入任务队列成功=======
2020-09-12 01:18:17.10 LOG [E:1 T:2732] - ======基于图像分析模式：加载dex=======
2020-09-12 01:18:17.16 LOG [E:1 T:2732] - =======加载dex完成=======
2020-09-12 01:18:17.161 LOG [E:1 T:2732] - ======校验无障碍功能======
2020-09-12 01:18:17.174 LOG [E:1 T:2732] - ---前置校验完成;启动系统--->>>>
2020-09-12 01:18:17.177 LOG [E:1 T:2732] - 版本信息：develop_version
2020-09-12 01:18:17.181 LOG [E:1 T:2732] - AutoJS version: 4.1.1 Alpha2
2020-09-12 01:18:17.183 LOG [E:1 T:2732] - device info: HUAWEI VOG-AL10 10
2020-09-12 01:18:17.186 LOG [E:1 T:2732] - 运行模式：多脚本调度运行 计时模式，超时时间：60 基于图像分析-使用OCR识别倒计时  排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 速度：200ms 底部高度：200
2020-09-12 01:18:17.187 LOG [E:1 T:2732] - 设备分辨率：[1080, 2340]
2020-09-12 01:18:17.193 LOG [E:1 T:2732] - ======解锁并校验截图权限======
2020-09-12 01:18:17.195 LOG [E:1 T:2732] - 已解锁
2020-09-12 01:18:17.196 LOG [E:1 T:2732] - 不需要重新锁定屏幕
2020-09-12 01:18:17.197 LOG [E:1 T:2732] - 解锁成功
2020-09-12 01:18:19.370 LOG [E:1 T:2732] - 请求截屏权限成功
2020-09-12 01:18:19.940 LOG [E:1 T:2732] - 已解锁
2020-09-12 01:18:19.943 LOG [E:1 T:2732] - 不需要重新锁定屏幕
2020-09-12 01:18:25.488 LOG [E:1 T:2732] - 立即开始
2020-09-12 01:18:25.499 LOG [E:1 T:2732] - 日期：2020-09-12，启动时能量:undefinedg
2020-09-12 01:18:40.782 LOG [E:2 T:2746] - ======尝试加入任务队列，并关闭重复运行的脚本=======
2020-09-12 01:18:40.799 LOG [E:2 T:2746] - ======加入任务队列成功=======
2020-09-12 01:18:40.801 LOG [E:2 T:2746] - ======基于图像分析模式：加载dex=======
2020-09-12 01:18:40.809 LOG [E:2 T:2746] - =======加载dex完成=======
2020-09-12 01:18:40.931 LOG [E:2 T:2746] - ======校验无障碍功能======
2020-09-12 01:18:40.940 LOG [E:2 T:2746] - ---前置校验完成;启动系统--->>>>
2020-09-12 01:18:40.942 LOG [E:2 T:2746] - 版本信息：develop_version
2020-09-12 01:18:40.944 LOG [E:2 T:2746] - AutoJS version: 4.1.1 Alpha2
2020-09-12 01:18:40.946 LOG [E:2 T:2746] - device info: HUAWEI VOG-AL10 10
2020-09-12 01:18:40.947 LOG [E:2 T:2746] - 运行模式：多脚本调度运行 计时模式，超时时间：60 基于图像分析-使用OCR识别倒计时  排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 速度：200ms 底部高度：200
2020-09-12 01:18:40.948 LOG [E:2 T:2746] - 设备分辨率：[1080, 2340]
2020-09-12 01:18:40.953 LOG [E:2 T:2746] - ======解锁并校验截图权限======
2020-09-12 01:18:40.954 LOG [E:2 T:2746] - 已解锁
2020-09-12 01:18:40.955 LOG [E:2 T:2746] - 不需要重新锁定屏幕
2020-09-12 01:18:40.956 LOG [E:2 T:2746] - 解锁成功
2020-09-12 01:18:43.105 LOG [E:2 T:2746] - 请求截屏权限成功
2020-09-12 01:18:43.642 LOG [E:2 T:2746] - 已解锁
2020-09-12 01:18:43.645 LOG [E:2 T:2746] - 不需要重新锁定屏幕
2020-09-12 01:23:01.28 LOG [E:4 T:2825] - ======尝试加入任务队列，并关闭重复运行的脚本=======
2020-09-12 01:23:01.69 LOG [E:4 T:2825] - ======加入任务队列成功=======
2020-09-12 01:23:01.73 LOG [E:4 T:2825] - ======基于图像分析模式：加载dex=======
2020-09-12 01:23:01.87 LOG [E:4 T:2825] - =======加载dex完成=======
2020-09-12 01:23:01.406 LOG [E:4 T:2825] - ======校验无障碍功能======
2020-09-12 01:23:01.422 LOG [E:4 T:2825] - ---前置校验完成;启动系统--->>>>
2020-09-12 01:23:01.426 LOG [E:4 T:2825] - 版本信息：develop_version
2020-09-12 01:23:01.431 LOG [E:4 T:2825] - AutoJS version: 4.1.1 Alpha2
2020-09-12 01:23:01.434 LOG [E:4 T:2825] - device info: HUAWEI VOG-AL10 10
2020-09-12 01:23:01.436 LOG [E:4 T:2825] - 运行模式：多脚本调度运行 计时模式，超时时间：60 基于图像分析-使用OCR识别倒计时  排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 速度：200ms 底部高度：200
2020-09-12 01:23:01.439 LOG [E:4 T:2825] - 设备分辨率：[1080, 2340]
2020-09-12 01:23:01.449 LOG [E:4 T:2825] - ======解锁并校验截图权限======
2020-09-12 01:23:01.452 LOG [E:4 T:2825] - 需要重新锁定屏幕

**Comment by nmcq** [comment]
2020-09-12 01:26:07.306 LOG [E:5 T:2843] - ======解锁并校验截图权限======
2020-09-12 01:26:07.307 LOG [E:5 T:2843] - 已解锁
2020-09-12 01:26:07.308 LOG [E:5 T:2843] - 不需要重新锁定屏幕
2020-09-12 01:26:07.309 LOG [E:5 T:2843] - 解锁成功
2020-09-12 01:26:07.515 DEBUG [E:5 T:2844] - 开始申请截图权限
2020-09-12 01:26:07.517 DEBUG [E:5 T:2844] - 已存储截图权限申请标记
2020-09-12 01:26:07.518 DEBUG [E:5 T:2844] - 已开启弹窗监测线程
2020-09-12 01:26:08.942 DEBUG [E:5 T:2845] - 点击"com.stardust.automator.UiObject@5784ff3; boundsInParent: Rect(0, 0 - 240, 162); boundsInScreen: Rect(729, 1332 - 969, 1494); packageName: com.android.systemui; className: android.widget.Button; text: 立即开始; contentDescription: null; viewId: android:id/button1; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_FOCUS, ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]"按钮
2020-09-12 01:26:09.323 DEBUG [E:5 T:2846] - 截图权限申请结果: true
2020-09-12 01:26:09.474 LOG [E:5 T:2843] - 请求截屏权限成功
2020-09-12 01:26:09.495 DEBUG [E:5 T:2843] - 获取截图耗时：19ms
2020-09-12 01:26:10.33 DEBUG [E:5 T:2843] - 获取到的倒计时时间：null
2020-09-12 01:26:10.35 DEBUG [E:5 T:2843] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":5,"timeout":1599846067120} 超时剩余时间：897秒
2020-09-12 01:26:10.37 DEBUG [E:5 T:2843] - 当前有任务正在运行：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":5,"timeout":1599846067120}
2020-09-12 01:26:10.38 DEBUG [E:5 T:2843] - 运行中脚本任务和当前任务相同，继续判断同源脚本是否正在运行
2020-09-12 01:26:10.39 DEBUG [E:5 T:2843] - 运行状态校验成功，执行后续功能
2020-09-12 01:26:10.42 DEBUG [E:5 T:2843] - 撤销自动任务：{"mDelay":0,"mInterval":0,"mLoopTimes":1,"mMillis":1599845166768,"mScheduled":true,"mScriptPath":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","mTimeFlag":0,"mId":2}
2020-09-12 01:26:10.45 LOG [E:5 T:2843] - 已解锁
2020-09-12 01:26:10.47 LOG [E:5 T:2843] - 不需要重新锁定屏幕
2020-09-12 01:26:10.82 DEBUG [E:5 T:2854] - isShowing：false isCanceled: true
2020-09-12 01:26:15.591 LOG [E:5 T:2843] - 立即开始
2020-09-12 01:26:15.597 LOG [E:5 T:2843] - 日期：2020-09-12，启动时能量:undefinedg
2020-09-12 01:26:15.598 INFO [E:5 T:2856] - 即将收取能量，运行中可按音量上键关闭
2020-09-12 01:26:15.601 DEBUG [E:5 T:2843] - 图片资源代理正常
2020-09-12 01:26:15.604 DEBUG [E:5 T:2843] - current time [1:26]
2020-09-12 01:26:15.606 WARN [E:5 T:2843] - 当前在限制运行时间范围，停止运行
2020-09-12 01:26:15.650 INFO [E:5 T:2843] - 脚本执行结束, 释放图片资源
2020-09-12 01:26:15.655 DEBUG [E:5 T:2843] - 释放图片，总数：1
2020-09-12 01:26:15.660 DEBUG [E:5 T:2843] - 同步释放所有图片，耗时2
2020-09-12 01:26:15.665 DEBUG [E:5 T:2843] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":5,"timeout":1599846067120} 超时剩余时间：891秒
2020-09-12 01:26:15.668 DEBUG [E:5 T:2843] - 准备移除运行中任务
2020-09-12 01:26:15.677 DEBUG [E:5 T:2843] - 校验并移除已加载的dex
2020-09-12 01:26:15.685 DEBUG [E:5 T:2843] - 队列小于等于1 不需要去重:null
2020-09-12 01:26:15.689 DEBUG [E:5 T:2843] - 无任务等待中
2020-09-12 01:26:15.693 INFO [E:5 T:2843] - 生命周期结束，准备关闭弹窗

**Comment by nmcq** [comment]
锁屏代码

/*
 * @Author: TonyJiangWJ
 * @Date: 2020-04-27 23:46:00
 * @Last Modified by: TonyJiangWJ
 * @Last Modified time: 2020-04-27 23:50:55
 * @Description: 
 */
let { config: _config } = require('../config.js')(runtime, this)

module.exports = function () {
  // MIUI 12 新控制中心
  
  sleep(500)
  home()
  sleep(500)
  // 点击锁屏按钮
  click(parseInt(_config.lock_x), parseInt(_config.lock_y))
}

**Comment by nmcq** [comment]
解锁代码

let { config: _config } = require('../config.js')(runtime, this)
module.exports = function (obj) {
  this.__proto__ = obj

  this.unlock = function () {
      click(571,1389)
      sleep(100)
      click(88,1555)
      sleep(100)
      click(737,1714)
      sleep(100)
      click(518,1565)
      sleep(100)
      click(708,1397)
      sleep(100)
      click(936,1404)
      sleep(100)
      click(805,1409)
      sleep(100)
      click(571,1389)
      sleep(100)
      click(805,1409)
      sleep(100)
      click(132,1398)
      
      
      
     
     // sleep(500)
    return this.check_lock()
  }


  /**
   * 一般情况下仅仅重写unlock即可，点亮、滑动、校验等等都在Unlock中实现了通用方式
   * 但是如果机型特殊，可以直接重写run_unlock()方法
   * 在run_unlock中编写自己的解锁方式
   */
//  this.run_unlock = function () {
    // 在这个里面编写解锁逻辑
  //}

  /**
   * 又或者只有某一个小方法不适用，可以只修改对应的方法即可
   * 具体方法见Unlock中定义的方法 比如failed、check_unlock、swipe_layer等等
   */
  

  
/**的方法 比如failed、check_unlock、swipe_layer等等
   */
  
}

**Comment by nmcq** [comment]
2020-09-12 02:13:11.616 INFO [E:30 T:3136] - 预订[3]分钟后的任务，时间戳:1599848171616
2020-09-12 02:13:11.702 DEBUG [E:30 T:3136] - 定时任务预定成功: 9
2020-09-12 02:13:11.707 DEBUG [E:30 T:3136] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":30,"timeout":1599848880358} 超时剩余时间：889秒
2020-09-12 02:13:11.708 DEBUG [E:30 T:3136] - 准备移除运行中任务
2020-09-12 02:13:11.731 DEBUG [E:30 T:3136] - 队列小于等于1 不需要去重:null
2020-09-12 02:13:11.744 DEBUG [E:30 T:3136] - 无任务等待中
2020-09-12 02:13:11.750 DEBUG [E:30 T:3136] - 设置脚本状态为执行完毕
2020-09-12 02:13:11.762 INFO [E:30 T:3136] - 脚本执行结束, 释放图片资源
2020-09-12 02:13:11.764 DEBUG [E:30 T:3136] - 释放图片，总数：0
2020-09-12 02:13:11.767 DEVELOP [E:30 T:3136] - resourceMonitor cost: 0ms
2020-09-12 02:13:11.769 WARN [E:30 T:3136] - 无任务在运行中，不可移除
2020-09-12 02:13:11.770 DEBUG [E:30 T:3136] - 校验并移除已加载的dex
2020-09-12 02:13:11.774 DEVELOP [E:30 T:3136] - common func cost: 0ms
2020-09-12 02:13:11.769 DEVELOP [E:30 T:3139] - unregisterEngineLifecycleCallback resourceMonitor
2020-09-12 02:13:11.774 DEVELOP [E:30 T:3140] - unregisterEngineLifecycleCallback common func
2020-09-12 02:13:11.777 DEVELOP [E:30 T:3139] - unregisterEngineLifecycleCallback resourceMonitor done
2020-09-12 02:13:11.779 DEVELOP [E:30 T:3140] - unregisterEngineLifecycleCallback common func done

**Comment by nmcq** [comment]
95 T:8502] - 图片资源代理替换images完毕
2020-09-12 09:31:02.145 LOG [E:95 T:8502] - ======校验无障碍功能======
2020-09-12 09:31:02.156 DEBUG [E:95 T:8502] - 当前已启用无障碍功能的服务:org.autojs.autojs/com.stardust.autojs.core.accessibility.AccessibilityService
2020-09-12 09:31:02.157 LOG [E:95 T:8502] - ---前置校验完成;启动系统--->>>>
2020-09-12 09:31:02.159 LOG [E:95 T:8502] - 版本信息：develop_version
2020-09-12 09:31:02.160 INFO [E:95 T:8502] - 本脚本免费使用，更多说明可前往github查阅README.md，地址：https://github.com/TonyJiangWJ/Ant-Forest
2020-09-12 09:31:02.161 LOG [E:95 T:8502] - AutoJS version: 4.1.1 Alpha2
2020-09-12 09:31:02.163 LOG [E:95 T:8502] - device info: HUAWEI VOG-AL10 10
2020-09-12 09:31:02.164 LOG [E:95 T:8502] - 运行模式：开发模式 单脚本运行无视运行队列 计时模式，超时时间：60 基于图像分析-使用OCR识别倒计时  排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 速度：200ms 底部高度：200
2020-09-12 09:31:02.165 LOG [E:95 T:8502] - 设备分辨率：[1080, 2340]
2020-09-12 09:31:02.167 WARN [E:95 T:8502] - 排行榜识别区域可不配置，脚本会自动识别
2020-09-12 09:31:02.168 WARN [E:95 T:8502] - 排行榜识别底部区域可不配置，脚本会自动识别，首次运行时自动识别需要一定时间，请不要手动关闭脚本
2020-09-12 09:31:02.169 WARN [E:95 T:8502] - 以上配置的详细内容请见README.md
2020-09-12 09:31:02.170 LOG [E:95 T:"8502] - ======解锁并校验截图权限======
2020-09-12 09:31:02.172 LOG [E:95 T:8502] - 需要重新锁定屏幕
2020-09-12 09:31:07.702 ERROR [E:95 T:8502] - 解锁发生异常, 三分钟后重新开始TypeError: Cannot find function check_lock in object [object Object].
2020-09-12 09:31:07.709 ERROR [E:95 T:8502] - fileName:file:/storage/emulated/0/脚本/Ant-Forest-master/extends/ExternalUnlockDevice.js line:30 typeof e:object
2020-09-12 09:31:07.719 ERROR [E:95 T:8502] - Cannot find function check_lock in object [object Object].

org.mozilla.javascript.EcmaError: TypeError: Cannot find function check_lock in object [object Object]. (file:/storage/emulated/0/脚本/Ant-Forest-master/extends/ExternalUnlockDevice.js#30)
at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4142)
at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4120)
at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4153)
at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4172)
at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4244)
at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2533)
at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2515)
at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1322)
at script(file:/storage/emulated/0/脚本/Ant-Forest-master/extends/ExternalUnlockDevice.js:30)
at script(file:/storage/emulated/0/脚本/Ant-Forest-master/lib/Unlock.js:189)
at script(file:/storage/emulated/0/脚本/Ant-Forest-master/lib/Unlock.js:225)
at script(/storage/emulated/0/脚本/Ant-Forest-master/main.js:123)
at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)
at org.mozilla.javascript.Script

**Comment by nmcq** [comment]
**已解决**
//解锁代码示例中，返回了 this.check_lock()
// 修改为  return this.check_unlock()  后，完美运行，锁屏功能也完美运行。
//需注意unlock.js中pin解锁代码中，也返回了 this.check_lock()
//日志中表现为- 解锁发生异常, 三分钟后重新开始TypeError: Cannot find function check_lock in object [object Object].
   }
    // 解锁完毕后返回check_lock方法，模块自动判断是否成功
    return this.check_lock()
  }
