### ISSUE TITLE
无法启动，一直在报错

### ISSUE THREAD

**Issue by shenghaomail** [TonyJiangWJ/Ant-Forest#59]
从介绍里下载的autojs和Ant-Forest-1.3.2.1。
把压缩包解压到手机自带的存储里，目录是/sdcard/脚本/
打开autojs，打开无障碍和悬浮窗权限，通过右下角加好导入main.js和config.js
在autojs里和在支付宝里通过悬浮窗执行main和config都报错，
运行config.js报错日志如下
`23:38:47.351/E: Error: Can't resolve relative module ID "./lib/prototype/CommonFunction.js" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)
Error: Can't resolve relative module ID "./lib/prototype/CommonFunction.js" when require() is used outside of a module
    at Require (file:///android_asset/modules/jvm-npm.js:89:0)
    at /storage/emulated/0/脚本/config.js:249:0`

运行main.js报错日志如下
`23:40:52.943/E: Error: Can't resolve relative module ID "./lib/SingletonRequirer.js" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)
Error: Can't resolve relative module ID "./lib/SingletonRequirer.js" when require() is used outside of a module
    at Require (file:///android_asset/modules/jvm-npm.js:89:0)
    at /storage/emulated/0/脚本/main.js:8:0`
大佬，帮忙看下

**Comment by shenghaomail** [comment]
脚本放错路径了，要放到autojs自动生成的“脚本”目录里
