### ISSUE TITLE
卡循环

### ISSUE THREAD

**Issue by Jonah-77** [TonyJiangWJ/Ant-Forest#64]
无限循环**上次收集有漏收，重新打开**，进入蚂蚁森林就会退出来，然后再进再退出无限循环

**Comment by Jonah-77** [comment]
还有深夜不支持运行，有时手动打开也会提示不在时间段内停止运行

**Comment by TonyJiangWJ** [comment]
麻烦提供日志

**Comment by Jonah-77** [comment]
我不太清楚应该提供哪部分的日志所以就将整个logs都发过来了，不周之处望见谅，请查看9月30日早六点多的那部分，出现有卡循环现象，之前也有过但时间已不记得了

文件使用**文叔叔网盘**发送，有效时间两日，若无法下载可回复我会及时补上[]()https://ws28.cn/f/3mhi5efumqw

**Comment by TonyJiangWJ** [comment]
```log
java.lang.ArrayIndexOutOfBoundsException: length=23; index=23
	at android.util.ContainerHelpers.binarySearch(ContainerHelpers.java:28)
	at android.util.SparseArray.put(SparseArray.java:238)
	at com.stardust.util.ResourceMonitor.onOpen(ResourceMonitor.java:48)
	at com.stardust.autojs.core.opencv.Mat.<init>(Mat.java:38)
```

`ResourceMonitor.onOpen` 这个似乎是因为你的AutoJS版本问题，是debug安装的 并不是release，免费版的源代码如果debug安装就会有这个问题，release版不会执行onOpen中的代码。
其源代码为：
```java
    public static void onOpen(ResourceMonitor.Resource resource) {
        //  release打包后 sEnable=false  会直接return
        if (!sEnabled) {
            return;
        }
        SparseArray<Exception> map = mResources.get(resource.getClass());
        if (map == null) {
            map = new SparseArray<>();
            mResources.put(resource.getClass(), map);
        }
        int resourceId = resource.getResourceId();
        Exception exception;
        if (sExceptionCreator == null) {
            exception = new ResourceMonitor.UnclosedResourceException(resource);
            exception.fillInStackTrace();
        } else {
            exception = sExceptionCreator.create(resource);
        }
        map.put(resourceId, exception);
    }

```
你可以下载release打包后的AutoJS进行使用 
-  [AutoJs 4.1.1 alpha2](http://47.110.40.234/autojs/autojs-4.1.1-alpha2.apk) or [AutoJS Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.20200908.apk)
- AutoJS Modify 是我修改过代码并打包的，增加了tess-two支持本地ocr识别，同时也修复了一些bug
 
另外的解锁异常，你是否自定义了解锁代码, 或者没有运行config.js输入锁屏密码？
```log
2020-09-30 10:12:39.695 解锁发生异常, 三分钟后重新开始JavaException: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
2020-09-30 10:12:39.695 fileName:<init> line:30 typeof e:object
2020-09-30 10:12:39.697 java.lang.ArrayIndexOutOfBoundsException: length=0; index=0

java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.stardust.automator.GlobalActionAutomator.pointsToPath(GlobalActionAutomator.kt:73)
	at com.stardust.automator.GlobalActionAutomator.gesture(GlobalActionAutomator.kt:67)
	at com.stardust.autojs.core.accessibility.SimpleActionAutomator.gesture(SimpleActionAutomator.kt:162)

```

**Comment by Jonah-77** [comment]
好的感谢，我已经更换为auto.js M

关于解锁异常问题：由于我并没有自动收能量的需求，所以每次我都是闲暇时手动开启，设置中的**计时最大等待时间**与**单次运行最大收集次数**也都改为了**1**   _刚看了下不知为何恢复默认了，我再改为**1**观察观察_   故并未设置解锁方面的内容
