### ISSUE TITLE
新版本始终循环“有漏收重新收取”

### ISSUE THREAD

**Issue by Yiyiyimu** [TonyJiangWJ/Ant-Forest#71]
error.log循环
```
2020-10-23 15:21:36.280 发生异常 [JavaException: java.lang.UnsupportedOperationException: Native object address is NULL]
2020-10-23 15:21:36.281 fileName:file:/storage/emulated/0/脚本/Ant-Forest-master/lib/OpenCvUtil.js line:45 typeof e:object
2020-10-23 15:21:36.282 java.lang.UnsupportedOperationException: Native object address is NULL

java.lang.UnsupportedOperationException: Native object address is NULL
	at org.opencv.core.Mat.<init>(Unknown Source:16)
	at org.opencv.core.MatOfInt.<init>(Unknown Source:0)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at org.mozilla.javascript.MemberBox.newInstance(Unknown Source:4)
	at org.mozilla.javascript.NativeJavaClass.constructInternal(Unknown Source:147)
	at org.mozilla.javascript.NativeJavaClass.constructSpecific(Unknown Source:0)
	at org.mozilla.javascript.NativeJavaClass.construct(Unknown Source:34)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source:2045)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source:69)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:20)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source:0)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source:33)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source:22)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(Unknown Source:43)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(Unknown Source:15)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(Unknown Source:0)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.֏(Unknown Source:2)
	at okhttp3.internal.io.ण.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:27)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(Unknown Source:1)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(Unknown Source:55)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:4)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(Unknown Source:29)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(Unknown Source:41)
	at java.lang.Thread.run(Thread.java:919)
```

warn.log 循环
```
2020-10-23 09:32:02.641 上一次收取有漏收，再次收集
2020-10-23 09:32:02.642 漏收原因：发生异常 [JavaException: java.lang.UnsupportedOperationException: Native object address is NULL]
```
```

**Comment by TonyJiangWJ** [comment]
安卓版本 以及 AutoJS版本分别是多少？

**Comment by Yiyiyimu** [comment]
MIUI12.0.1, Pro8.0.0-5

**Comment by TonyJiangWJ** [comment]
是安卓版本；
另外AutoJS试试其他版本 [AutoJS Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.20200923.apk)

**Comment by Yiyiyimu** [comment]
不好意思 android q

**Comment by Yiyiyimu** [comment]
因为我还有一份1.3.0.6.8是没有这个问题的，感觉应该不是autojs的问题

**Comment by TonyJiangWJ** [comment]
新版本加了新的检测方式，还没有测试过其他版本的AutoJS 所以应该是不兼容导致的

**Comment by Yiyiyimu** [comment]
> 新版本加了新的检测方式，还没有测试过其他版本的AutoJS 所以应该是不兼容导致的

噢看到了，我试试免费版本，谢谢

**Comment by TonyJiangWJ** [comment]
你可以先取消勾选 `是否通过findCircles识别能量球` 不过这个在后续版本中我删掉了 -.-

**Comment by Yiyiyimu** [comment]
用你编译的AutoJS版本没问题了，我也就不自己改了hh，多谢多谢🙏🙏

**Comment by TonyJiangWJ** [comment]
新版本修复了这个问题 `v1.3.3.3`

**Comment by Yiyiyimu** [comment]
> 新版本修复了这个问题 `v1.3.3.3`

感谢！
